### ISSUE TITLE
Issue in worldLoader.py: unable to read file buffer

### ISSUE THREAD

**Issue by avdstaaij** [avdstaaij/gdpc#43]
Moved from https://github.com/nilsgawlik/gdmc_http_client_python/issues/73, by @HSTEHSTEHSTE:
See https://github.com/nilsgawlik/gdmc_http_client_python/issues/73 for more discussion.

---

Line 57 in worldLoader.py is unable to read file buffer:

`
Error: Internal server error: java.util.ConcurrentModificationException Traceback (most recent call last): File "c:\Users\HSTE\GMDC_2022\examples\simple_village.py", line 64, in <module> WORLDSLICE = WL.WorldSlice(STARTX, STARTZ, File "C:\Users\HSTE\AppData\Local\Programs\Python\Python39\lib\site-packages\gdpc\worldLoader.py", line 58, in __init__ self.nbtfile = nbt.nbt.NBTFile(buffer=file_like) File "C:\Users\HSTE\AppData\Local\Programs\Python\Python39\lib\site-packages\nbt\nbt.py", line 641, in __init__ self.parse_file() File "C:\Users\HSTE\AppData\Local\Programs\Python\Python39\lib\site-packages\nbt\nbt.py", line 675, in parse_file raise MalformedFileError( nbt.nbt.MalformedFileError: First record is not a Compound Tag
`

Adding a print statement just before the NBT file load solves the issue (albeit in unsatisfactory manner).

Could some shed some light on what might be causing the issue? Thanks!

**Comment by avdstaaij** [comment]
Just like #18 and #34, I cannot reproduce this bug. I suspect it has been solved somewhere along the way, given how much GDPC and GDMC-HTTP have changed since it was posted. I'm closing this issue, but feel free to open a new one if the bug still occurs.
